### ISSUE TITLE
Move API intro to somewhere earlier?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/ropensci-review-tools#10]
In the description of the stdlogs endpoint there is

>  The functions are all controlled by the roreviewapi package, which is in turn a plumber API providing access to the functionality of the pkgcheck package.

Shouldn't this come earlier?

**Comment by mpadge** [comment]
Yep, and the whole first bit when it does come earlier should be rewritten and clarified. Which the above commit has (hopefully) done. Thanks for the nudge.
